DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
  ID IDENTITY,
  EMAIL VARCHAR(100) NOT NULL,
  NAME VARCHAR(100) ,
  SURNAME VARCHAR(300),
  PASSWORD VARCHAR(50) NOT NULL,
  PHONE VARCHAR(9),
  ADDRESS VARCHAR(150)
);

INSERT INTO CUSTOMER(EMAIL,PASSWORD) VALUES('prueba@domain.com','Prueba');